/* Copyright (C) 2007 - 2011 YOOtheme GmbH, YOOtheme Proprietary Use License (http://www.yootheme.com/license) */

(function(d){var f=function(){};d.extend(f.prototype,{name:"Googlemaps",options:{lat:53.553407,lng:9.992196,marker:true,popup:false,text:"",zoom:13,mapCtrl:2,zoomWhl:true,mapType:0,typeCtrl:true,overviewCtrl:true,directions:true,directionsDestUpdate:false,directionsTravelMode:0,locale:"en",mainIcon:"red-dot",otherIcon:"blue-dot",iconUrl:"http://maps.google.com/mapfiles/ms/micons/",msgFromAddress:"From address: ",msgGetDirections:"Get directions",msgEmpty:"Please fill in your address.",msgNotFound:"Sorry, address not found!",
msgAddressNotFound:", not found!"},initialize:function(a,b){this.options=d.extend({},this.options,b);this.container=a;this.setupMap();this.options.directions&&this.setupDirections()},setupMap:function(){this.map=new google.maps.Map(this.container.get(0),{mapTypeId:google.maps.MapTypeId.ROADMAP});this.map.setOptions({navigationControl:this.options.mapCtrl==1||this.options.mapCtrl==2?true:false});this.map.setOptions({navigationControlOptions:{style:this.options.mapCtrl==1?google.maps.NavigationControlStyle.SMALL:
google.maps.NavigationControlStyle.DEFAULT}});this.map.setOptions({scrollwheel:this.options.zoomWhl?true:false});this.options.mapType==1&&this.map.setOptions({mapTypeId:google.maps.MapTypeId.SATELLITE});this.options.mapType==2&&this.map.setOptions({mapTypeId:google.maps.MapTypeId.HYBRID});this.map.setOptions({mapTypeControl:this.options.typeCtrl?true:false});this.infowindow=new google.maps.InfoWindow;this.options.marker?this.addMarkerLatLng(this.options.lat,this.options.lng,this.options.text,true):
this.centerMap(this.options.lat,this.options.lng)},createMarker:function(a,b,c){var e=this,g=this.map,i=this.infowindow,j=new google.maps.MarkerImage(this.options.iconUrl+c+".png",new google.maps.Size(32,32),new google.maps.Point(0,0),new google.maps.Point(16,32));c=c.match("pushpin")?this.options.iconUrl+"pushpin_shadow.png":this.options.iconUrl+"msmarker.shadow.png";c=new google.maps.MarkerImage(c,new google.maps.Size(56,32),new google.maps.Point(0,0),new google.maps.Point(16,32));var h=new google.maps.Marker({position:a,
icon:j,shadow:c,map:this.map});if(b||this.options.directionsDestUpdate)google.maps.event.addListener(h,"click",function(){if(b){i.setContent(b);i.open(g,h)}if(e.options.directionsDestUpdate){e.options.lat=h.getPosition().lat();e.options.lng=h.getPosition().lng()}});return h},centerMap:function(a,b){this.map.setCenter(new google.maps.LatLng(a,b));this.map.setZoom(this.options.zoom)},addMarkerLatLng:function(a,b,c,e){var g=this.options.otherIcon;if(e)g=this.options.mainIcon;a=new google.maps.LatLng(a,
b);g=this.createMarker(a,c,g);if(e){this.map.setCenter(a);this.map.setZoom(this.options.zoom)}if(e&&c&&this.options.popup){this.infowindow.setContent(c);this.infowindow.open(this.map,g)}},setupDirections:function(){var a=this;this.directionsService=new google.maps.DirectionsService;this.directionsDisplay=new google.maps.DirectionsRenderer;this.directionsDisplay.setMap(this.map);this.directionsDisplay.setPanel(d("<div>").addClass("directions").css("position","relative").insertAfter(this.container).get(0));
var b=d("<p>").append('<label for="from-address">'+this.options.msgFromAddress+"</label>").append('<input type="text" name="address" style="margin:0 5px;" />').append('<button type="submit">'+this.options.msgGetDirections+"</button>");d('<form method="get" action="#">').append(b).insertAfter(this.container).bind("submit",function(c){c.preventDefault();c.stopPropagation();a.setDirections(d(this))})},setDirections:function(a){var b=this;this.container.parent().find("div.alert").remove();a=a.find('input[name="address"]').val();
a===""?this.showAlert(this.options.msgEmpty):this.directionsService.route({origin:a,destination:new google.maps.LatLng(this.options.lat,this.options.lng),travelMode:google.maps.DirectionsTravelMode.DRIVING,region:this.options.locale},function(c,e){e==google.maps.DirectionsStatus.OK?b.directionsDisplay.setDirections(c):b.showAlert(b.options.msgNotFound)})},showAlert:function(a){d("<div>").addClass("alert").append(d("<strong>").text(a)).insertAfter(this.container)}});d.fn[f.prototype.name]=function(){var a=
arguments,b=a[0]?a[0]:null;return this.each(function(){var c=d(this);if(f.prototype[b]&&c.data(f.prototype.name)&&b!="initialize")c.data(f.prototype.name)[b].apply(c.data(f.prototype.name),Array.prototype.slice.call(a,1));else if(!b||d.isPlainObject(b)){var e=new f;f.prototype.initialize&&e.initialize.apply(e,d.merge([c],a));c.data(f.prototype.name,e)}else d.error("Method "+b+" does not exist on jQuery."+f.name)})}})(jQuery);
